"""Application constants and configuration."""

APP_NAME = "System Monitor Pro"
APP_VERSION = "1.0.0"
APP_AUTHOR = "SystemMonitor Team"

# Update intervals (milliseconds)
UPDATE_INTERVAL_FAST = 1000
UPDATE_INTERVAL_NORMAL = 2000
UPDATE_INTERVAL_SLOW = 5000

# Chart settings
CHART_HISTORY_LENGTH = 60
CHART_UPDATE_INTERVAL = 1000

# Process table settings
PROCESS_REFRESH_INTERVAL = 2000
PROCESS_PAGE_SIZE = 50

# Colors
COLOR_CPU = "#3B82F6"
COLOR_MEMORY = "#10B981"
COLOR_DISK = "#F59E0B"
COLOR_NETWORK = "#EF4444"
COLOR_GPU = "#8B5CF6"
COLOR_TEMP = "#F97316"
COLOR_SUCCESS = "#10B981"
COLOR_WARNING = "#F59E0B"
COLOR_INFO = "#3B82F6"

# Thresholds
CPU_WARNING = 70
CPU_CRITICAL = 90
MEMORY_WARNING = 80
MEMORY_CRITICAL = 95
DISK_WARNING = 85
DISK_CRITICAL = 95
TEMP_WARNING = 75
TEMP_CRITICAL = 85

# Default theme
DEFAULT_THEME = "dark"
DEFAULT_COLOR_THEME = "blue"
